# Generated by Django 5.2.6 on 2026-01-30 10:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event', max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event', max_length=1000, null=True)),
                ('event_date', models.DateTimeField(help_text='Date and time when the event will occur')),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('special_day', 'Special Day'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('training', 'Training'), ('team_building', 'Team Building'), ('client_meeting', 'Client Meeting'), ('project_review', 'Project Review'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('holiday', 'Holiday'), ('deadline', 'Deadline'), ('presentation', 'Presentation'), ('other', 'Other')], default='meeting', help_text='Type of the event', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Physical or virtual location of the event', max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', help_text='Current status of the event', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration of the event in minutes', null=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this event repeats regularly')),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='How often the event repeats', max_length=50, null=True)),
                ('assigned_employee', models.ForeignKey(help_text='Employee assigned to this event', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this event', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['event_date'],
                'indexes': [models.Index(fields=['event_date'], name='events_event_d_ec8074_idx'), models.Index(fields=['event_type'], name='events_event_t_c9f56c_idx'), models.Index(fields=['assigned_employee'], name='events_assigne_db712c_idx'), models.Index(fields=['status'], name='events_status_8890b6_idx')],
            },
        ),
    ]
