# Generated by Django 5.2.6 on 2026-02-14 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_for_all_employees',
            field=models.BooleanField(default=False, help_text='If true, this event is visible to all employees'),
        ),
        migrations.AlterField(
            model_name='event',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, help_text='Employee assigned to this event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
