# Generated by Django 5.2.6 on 2025-11-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_event_date_future_and_more'),
    ]

    operations = [
    ]
