# Generated by Django 5.2.6 on 2025-11-03 08:53

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20251103_0852'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_date_future',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('event_date__gte', datetime.datetime(2025, 11, 3, 8, 53, 26, 540474, tzinfo=datetime.timezone.utc))), name='event_date_future'),
        ),
    ]
