# Generated by Django 5.2.6 on 2025-11-21 08:54

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_event_date_future_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_date_future',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('event_date__gte', datetime.datetime(2025, 11, 21, 8, 54, 34, 423129, tzinfo=datetime.timezone.utc))), name='event_date_future'),
        ),
    ]
