# Generated by Django 5.2.6 on 2026-01-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_contentverification_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentverification',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
