# Generated by Django 5.2.6 on 2026-01-17 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0020_remove_clientdocument_description_and_more'),
        ('verification', '0003_alter_contentverification_verification_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('poster', 'Poster'), ('reel', 'Reel'), ('story', 'Story')], max_length=10)),
                ('completion_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='clientapp.client')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Verification',
                'verbose_name_plural': 'Content Verifications',
                'ordering': ['-completion_date'],
            },
        ),
        migrations.DeleteModel(
            name='ContentVerification',
        ),
    ]
