# Generated by Django 5.2.6 on 2026-01-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_clientverification_delete_contentverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientverification',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
