# Generated by Django 5.2.6 on 2026-01-20 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_alter_clientverification_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientverification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clientverification',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
