# Generated by Django 5.2.6 on 2026-01-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_alter_clientverification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
