# Generated by Django 5.2.6 on 2026-01-30 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0007_alter_clientverification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientverification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clientverification',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
