# Generated by Django 5.2.6 on 2026-02-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0010_alter_clientverification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientverification',
            name='verified_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
