# Generated by Django 5.2.6 on 2026-02-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0011_clientverification_verified_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientverification',
            name='verified_month',
        ),
    ]
