# Generated by Django 5.2.6 on 2026-02-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0012_remove_clientverification_verified_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientverification',
            options={},
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='description',
        ),
    ]
