# Generated by Django 5.2.6 on 2026-02-04 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0013_alter_clientverification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientverification',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('poster', 'Poster'), ('reel', 'Reel'), ('story', 'Story')], default='video', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientverification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
