# Generated by Django 5.2.6 on 2026-02-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0014_clientverification_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientverification',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('poster', 'Poster')], max_length=10),
        ),
    ]
