# Generated by Django 5.2.6 on 2026-02-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0015_alter_clientverification_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientverification',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
