# Generated by Django 5.2.6 on 2026-02-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0017_remove_clientverification_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientverification',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
