# Generated by Django 5.2.6 on 2026-02-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0018_clientverification_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientverification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='count',
        ),
        migrations.AddField(
            model_name='clientverification',
            name='poster_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='video_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
