# Generated by Django 5.2.6 on 2026-02-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0019_remove_clientverification_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientverification',
            name='poster_count',
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='video_count',
        ),
        migrations.AddField(
            model_name='clientverification',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('poster', 'Poster')], default='poster', max_length=10),
        ),
    ]
