# Generated by Django 5.2.6 on 2026-02-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0020_remove_clientverification_poster_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientverification',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
