# Generated by Django 5.2.6 on 2026-02-10 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0022_client_created_by'),
        ('verification', '0021_alter_clientverification_completion_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientverification',
            options={'ordering': ['-posted_date', '-created_at'], 'verbose_name': 'Posted Content', 'verbose_name_plural': 'Posted Contents'},
        ),
        migrations.RenameField(
            model_name='clientverification',
            old_name='completion_date',
            new_name='posted_date',
        ),
        migrations.AddField(
            model_name='clientverification',
            name='content_url',
            field=models.URLField(blank=True, null=True, verbose_name='Content URL'),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='platform',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='posted', max_length=20),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientverification',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('poster', 'Poster')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clientverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='clientverification',
            index=models.Index(fields=['client', 'posted_date'], name='verificatio_client__3a3d54_idx'),
        ),
        migrations.AddIndex(
            model_name='clientverification',
            index=models.Index(fields=['posted_date', 'status'], name='verificatio_posted__7ae55a_idx'),
        ),
    ]
