# Generated by Django 5.2.6 on 2026-02-11 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0022_client_created_by'),
        ('verification', '0022_alter_clientverification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_verifications', to='clientapp.client')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Verification',
                'verbose_name_plural': 'Monthly Verifications',
                'ordering': ['-year', '-month'],
                'unique_together': {('client', 'month', 'year')},
            },
        ),
    ]
