# Generated by Django 5.2.6 on 2026-02-11 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0023_monthlyverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientverification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Posted Content', 'verbose_name_plural': 'Posted Contents'},
        ),
        migrations.AlterModelOptions(
            name='monthlyverification',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='clientverification',
            name='verificatio_client__3a3d54_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientverification',
            name='verificatio_posted__7ae55a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='monthlyverification',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='content_url',
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='posted_date',
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='clientverification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='clientverification',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlyverification',
            name='clientverification',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_verifications', to='verification.clientverification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyverification',
            name='posters_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyverification',
            name='posters_posted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyverification',
            name='videos_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyverification',
            name='videos_posted',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='monthlyverification',
            name='client',
        ),
        migrations.RemoveField(
            model_name='monthlyverification',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='monthlyverification',
            name='month',
        ),
        migrations.RemoveField(
            model_name='monthlyverification',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='monthlyverification',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='monthlyverification',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='monthlyverification',
            name='year',
        ),
    ]
