# Generated by Django 5.2.6 on 2026-02-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0024_alter_clientverification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientverification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='monthlyverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlyverification',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyverification',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
