# Generated by Django 5.2.6 on 2026-01-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_income_gst_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
