# Generated by Django 5.2.6 on 2026-01-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_income_gst_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
