# Generated by Django 5.2.6 on 2025-10-07 06:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, unique=True)),
                ('client_type', models.CharField(choices=[('company', 'Company'), ('brand', 'Brand'), ('individual', 'Individual'), ('agency', 'Agency')], default='company', max_length=20)),
                ('industry', models.CharField(blank=True, choices=[('fashion', 'Fashion & Apparel'), ('beauty', 'Beauty & Cosmetics'), ('health', 'Health & Wellness'), ('food_beverage', 'Food & Beverage'), ('technology', 'Technology'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('retail', 'Retail'), ('other', 'Other')], max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('instagram_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram ID/Handle')),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook ID/Page')),
                ('youtube_channel', models.CharField(blank=True, max_length=255, null=True, verbose_name='YouTube Channel')),
                ('google_my_business', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google My Business')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('twitter_handle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter Handle')),
                ('videos_per_month', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Videos per Month')),
                ('posters_per_month', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Posters per Month')),
                ('reels_per_month', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Reels per Month')),
                ('stories_per_month', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Stories per Month')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_hold', 'On Hold'), ('terminated', 'Terminated'), ('prospect', 'Prospect')], default='prospect', max_length=20)),
                ('onboarding_date', models.DateField(default=django.utils.timezone.now)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_retainer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Retainer Fee')),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['manager', 'team_lead']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Contract Agreement'), ('proposal', 'Proposal'), ('invoice', 'Invoice'), ('nda', 'Non-Disclosure Agreement'), ('brand_guidelines', 'Brand Guidelines'), ('marketing_plan', 'Marketing Plan'), ('performance_report', 'Performance Report'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='client_documents/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clientapp.client')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_client_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clientapp.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientContentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('videos_delivered', models.PositiveIntegerField(default=0)),
                ('posters_delivered', models.PositiveIntegerField(default=0)),
                ('reels_delivered', models.PositiveIntegerField(default=0)),
                ('stories_delivered', models.PositiveIntegerField(default=0)),
                ('delivered_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_deliveries', to='clientapp.client')),
                ('delivered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Delivery',
                'verbose_name_plural': 'Content Deliveries',
                'unique_together': {('client', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ClientSocialMediaAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('google_business', 'Google My Business')], max_length=20)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monthly_impressions', models.PositiveIntegerField(default=0)),
                ('monthly_reach', models.PositiveIntegerField(default=0)),
                ('analytics_date', models.DateField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_analytics', to='clientapp.client')),
            ],
            options={
                'verbose_name': 'Social Media Analytics',
                'verbose_name_plural': 'Social Media Analytics',
                'unique_together': {('client', 'platform', 'analytics_date')},
            },
        ),
    ]
