# Generated by Django 5.2.6 on 2025-10-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Client Description'),
        ),
    ]
