# Generated by Django 5.2.6 on 2025-10-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_client_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientnote',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientnote',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='clientsocialmediaanalytics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clientsocialmediaanalytics',
            name='client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='account_manager',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_terms',
        ),
        migrations.DeleteModel(
            name='ClientContentDelivery',
        ),
        migrations.DeleteModel(
            name='ClientNote',
        ),
        migrations.DeleteModel(
            name='ClientSocialMediaAnalytics',
        ),
    ]
