# Generated by Django 5.2.6 on 2025-10-31 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_remove_clientnote_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='current_month_payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('partial', 'Partial Payment')], default='pending', max_length=20, verbose_name='Current Month Payment Status'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Payment Date'),
        ),
        migrations.AddField(
            model_name='client',
            name='next_payment_date',
            field=models.DateField(blank=True, help_text='Automatically calculated next payment due date', null=True, verbose_name='Next Payment Due Date'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20, verbose_name='Payment Cycle'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_date',
            field=models.PositiveIntegerField(default=1, help_text='Enter the day of month (1-31) when payment is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(31)], verbose_name='Payment Date (Day of Month)'),
        ),
    ]
