# Generated by Django 5.2.6 on 2025-10-31 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_client_current_month_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='early_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Early Payment Amount'),
        ),
        migrations.AddField(
            model_name='client',
            name='early_payment_date',
            field=models.DateField(blank=True, help_text='Date when early payment was made', null=True, verbose_name='Early Payment Date'),
        ),
        migrations.AddField(
            model_name='client',
            name='early_payment_notes',
            field=models.TextField(blank=True, help_text='Any notes regarding early payment', null=True, verbose_name='Early Payment Notes'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_timing',
            field=models.CharField(choices=[('on_time', 'On Time'), ('early', 'Early'), ('late', 'Late')], default='on_time', help_text='Indicates if payment was made early, on time, or late', max_length=10, verbose_name='Payment Timing'),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_month_payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('partial', 'Partial Payment'), ('early_paid', 'Early Paid')], default='pending', max_length=20, verbose_name='Current Month Payment Status'),
        ),
    ]
