# Generated by Django 5.2.6 on 2025-11-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_client_early_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('contract', 'Contract Agreement'), ('proposal', 'Proposal'), ('invoice', 'Invoice'), ('gst_document', 'GST Document'), ('nda', 'Non-Disclosure Agreement'), ('brand_guidelines', 'Brand Guidelines'), ('marketing_plan', 'Marketing Plan'), ('performance_report', 'Performance Report'), ('other', 'Other')], max_length=50),
        ),
    ]
