# Generated by Django 5.2.6 on 2025-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_alter_clientdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
