# Generated by Django 5.2.6 on 2025-12-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0007_client_deleted_at_client_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
