# Generated by Django 5.2.6 on 2026-01-06 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_alter_clientdocument_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_date',
            field=models.PositiveIntegerField(default=1, help_text='Enter the day of month (1-31) when payment is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Payment Date (Day of Month)'),
        ),
    ]
