# Generated by Django 5.2.6 on 2026-01-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0009_alter_client_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='current_month_payment_status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='early_payment_amount',
        ),
        migrations.RemoveField(
            model_name='client',
            name='early_payment_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='early_payment_notes',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='monthly_retainer',
        ),
        migrations.RemoveField(
            model_name='client',
            name='next_payment_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_cycle',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_timing',
        ),
    ]
