# Generated by Django 5.2.6 on 2026-01-08 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0010_remove_client_current_month_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='current_month_payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('partial', 'Partial Payment'), ('early_paid', 'Early Paid')], default='pending', max_length=20, verbose_name='Current Month Payment Status'),
        ),
        migrations.AddField(
            model_name='client',
            name='early_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Early Payment Amount'),
        ),
        migrations.AddField(
            model_name='client',
            name='early_payment_date',
            field=models.DateField(blank=True, help_text='Date when early payment was made', null=True, verbose_name='Early Payment Date'),
        ),
        migrations.AddField(
            model_name='client',
            name='early_payment_notes',
            field=models.TextField(blank=True, help_text='Any notes regarding early payment', null=True, verbose_name='Early Payment Notes'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Payment Date'),
        ),
        migrations.AddField(
            model_name='client',
            name='monthly_retainer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Retainer Fee'),
        ),
        migrations.AddField(
            model_name='client',
            name='next_payment_date',
            field=models.DateField(blank=True, help_text='Automatically calculated next payment due date', null=True, verbose_name='Next Payment Due Date'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20, verbose_name='Payment Cycle'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_date',
            field=models.PositiveIntegerField(default=1, help_text='Enter the day of month (1-31) when payment is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Payment Date (Day of Month)'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_timing',
            field=models.CharField(choices=[('on_time', 'On Time'), ('early', 'Early'), ('late', 'Late')], default='on_time', help_text='Indicates if payment was made early, on time, or late', max_length=10, verbose_name='Payment Timing'),
        ),
    ]
