# Generated by Django 5.2.6 on 2026-01-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0012_clientadminnote_clientpaymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='early_payment_amount',
        ),
        migrations.RemoveField(
            model_name='client',
            name='early_payment_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='early_payment_notes',
        ),
    ]
