# Generated by Django 5.2.6 on 2026-01-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0014_clientpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientPaymentHistory',
        ),
    ]
