# Generated by Django 5.2.6 on 2026-01-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0015_delete_clientpaymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clientdocument',
            name='title',
        ),
    ]
