# Generated by Django 5.2.6 on 2026-01-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0016_remove_clientdocument_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
