# Generated by Django 5.2.6 on 2026-01-20 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0020_remove_clientdocument_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_date',
            field=models.PositiveIntegerField(default=31, help_text='The system now defaults to the last day of the month for all payments.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Default Payment Day'),
        ),
        migrations.DeleteModel(
            name='ClientAdminNote',
        ),
    ]
