# Generated by Django 5.2.6 on 2026-02-11 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0022_client_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='base_posters_per_month',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base Posters per Month'),
        ),
        migrations.AddField(
            model_name='client',
            name='base_videos_per_month',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base Videos per Month'),
        ),
    ]
