# Generated by Django 5.2.6 on 2026-02-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0024_backfill_quotas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='onboarding_date',
        ),
    ]
