# Generated by Django 5.2.6 on 2026-02-14 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0025_remove_client_onboarding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(default='legacy@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(default='+0000000000', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.CharField(choices=[('fashion', 'Fashion & Apparel'), ('beauty', 'Beauty & Cosmetics'), ('health', 'Health & Wellness'), ('food_beverage', 'Food & Beverage'), ('technology', 'Technology'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('retail', 'Retail'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='monthly_retainer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Retainer Fee'),
        ),
        migrations.AlterField(
            model_name='client',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
