# Generated by Django 5.2.6 on 2026-02-14 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0026_alter_client_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(default='+0000000000', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be valid (10-20 chars, allowing spaces, dashes, parentheses).', regex='^\\+?[\\d\\s\\-\\(\\)]{10,20}$')]),
        ),
    ]
