# Generated by Django 5.2.6 on 2025-11-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0002_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (optional)', null=True, upload_to='profile_images/%Y/%m/%d/', verbose_name='Profile Image'),
        ),
    ]
