# Generated by Django 5.2.6 on 2025-12-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
