# Generated by Django 5.2.6 on 2025-12-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0004_alter_employeedocument_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemedia',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
