# Generated by Django 5.2.6 on 2026-01-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0005_alter_employeemedia_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='title',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
