# Generated by Django 5.2.6 on 2026-01-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0006_remove_employeedocument_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemedia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employeemedia',
            name='title',
        ),
    ]
