# Generated by Django 5.2.6 on 2026-01-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0007_remove_employeemedia_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('developer', 'Developer'), ('camera_department', 'Camera Department'), ('editor', 'Editor'), ('marketer', 'Marketer'), ('hr', 'HR'), ('manager', 'Manager'), ('content_creator', 'Content Creator')], help_text='Specific role type for the employee', max_length=50, null=True),
        ),
    ]
