# Generated by Django 5.2.6 on 2026-01-06 05:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0009_alter_client_payment_date'),
        ('emplyees', '0008_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_folder_name', models.CharField(max_length=255)),
                ('nested_folders', models.TextField(blank=True, help_text='List or describe nested folders', null=True)),
                ('nested_files', models.TextField(blank=True, help_text='List or describe nested files', null=True)),
                ('drive_link', models.URLField()),
                ('uploaded_date', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('link', models.URLField(blank=True, help_text='Additional social media or reference link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_department_projects', to='clientapp.client')),
            ],
            options={
                'verbose_name': 'Camera Department Project',
                'verbose_name_plural': 'Camera Department Projects',
                'ordering': ['-uploaded_date'],
            },
        ),
    ]
