# Generated by Django 5.2.6 on 2026-01-06 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0009_cameradepartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameradepartment',
            name='drive_link',
        ),
        migrations.RemoveField(
            model_name='cameradepartment',
            name='main_folder_name',
        ),
        migrations.RemoveField(
            model_name='cameradepartment',
            name='nested_files',
        ),
        migrations.RemoveField(
            model_name='cameradepartment',
            name='nested_folders',
        ),
        migrations.AlterField(
            model_name='cameradepartment',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.CreateModel(
            name='CameraFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('drive_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='emplyees.cameradepartment')),
            ],
        ),
        migrations.CreateModel(
            name='CameraFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('drive_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='emplyees.camerafolder')),
            ],
        ),
    ]
