# Generated by Django 5.2.6 on 2026-01-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0010_remove_cameradepartment_drive_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerafolder',
            name='project',
        ),
        migrations.AddField(
            model_name='cameradepartment',
            name='folders_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='CameraFile',
        ),
        migrations.DeleteModel(
            name='CameraFolder',
        ),
    ]
