# Generated by Django 5.2.6 on 2026-01-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0011_remove_camerafolder_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameradepartment',
            name='folders_data',
        ),
    ]
