# Generated by Django 5.2.6 on 2026-01-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0012_remove_cameradepartment_folders_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameradepartment',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
