# Generated by Django 5.2.6 on 2026-01-07 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0009_alter_client_payment_date'),
        ('emplyees', '0014_cameradepartment_employee_leavemanagement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameradepartment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_department_projects', to='clientapp.client'),
        ),
    ]
