# Generated by Django 5.2.6 on 2026-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0015_alter_cameradepartment_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salary_payment',
            field=models.BooleanField(default=False, help_text='Has the employee been paid their salary?'),
        ),
    ]
