# Generated by Django 5.2.6 on 2026-01-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0016_customuser_salary_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryhistory',
            options={'verbose_name': 'Salary History', 'verbose_name_plural': 'Salary History'},
        ),
        migrations.RenameField(
            model_name='salaryhistory',
            old_name='changed_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='salaryhistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='salaryhistory',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='salaryhistory',
            name='effective_to',
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='incentive',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
