# Generated by Django 5.2.6 on 2026-01-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0017_alter_salaryhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
