# Generated by Django 5.2.6 on 2026-01-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0018_alter_salaryhistory_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='salary_payment',
        ),
    ]
