# Generated by Django 5.2.6 on 2026-01-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0020_adminnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnote',
            name='created_by',
        ),
    ]
