# Generated by Django 5.2.6 on 2026-01-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0023_salarypayment_delete_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemedia',
            name='media_type',
            field=models.CharField(choices=[('profile_picture', 'Profile Picture'), ('id_photo', 'ID Photo'), ('id_card_photo', 'ID Card Photo'), ('signature', 'Signature'), ('work_sample', 'Work Sample'), ('training_certificate', 'Training Certificate'), ('award_certificate', 'Award Certificate'), ('other', 'Other')], max_length=50),
        ),
    ]
