# Generated by Django 5.2.6 on 2026-01-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0024_alter_employeemedia_media_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavemanagement',
            old_name='rejection_reason',
            new_name='remarks',
        ),
    ]
