# Generated by Django 5.2.6 on 2026-01-16 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0025_rename_rejection_reason_leavemanagement_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemanagement',
            name='category',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('bereavement', 'Bereavement Leave'), ('lop', 'Leave Without Pay (LOP)'), ('wfh', 'Work From Home (WFH)'), ('other', 'Other')], max_length=20, verbose_name='Category of Leave'),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_total', models.DecimalField(decimal_places=1, default=18.0, max_digits=5)),
                ('casual_total', models.DecimalField(decimal_places=1, default=12.0, max_digits=5)),
                ('sick_total', models.DecimalField(decimal_places=1, default=6.0, max_digits=5)),
                ('year', models.IntegerField(default=2026)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
