# Generated by Django 5.2.6 on 2026-01-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0026_alter_leavemanagement_category_leavebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemanagement',
            name='category',
            field=models.CharField(choices=[('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Bereavement Leave', 'Bereavement Leave'), ('LOP', 'Leave Without Pay (LOP)'), ('WFH', 'Work From Home (WFH)'), ('Other', 'Other')], max_length=20, verbose_name='Category of Leave'),
        ),
    ]
