# Generated by Django 5.2.6 on 2026-01-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0027_alter_leavemanagement_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemanagement',
            name='address_during_leave',
        ),
        migrations.DeleteModel(
            name='AdminNote',
        ),
    ]
