# Generated by Django 5.2.6 on 2026-01-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0028_remove_leavemanagement_address_during_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemanagement',
            name='address_during_leave',
            field=models.TextField(blank=True, null=True, verbose_name='Address During Leave'),
        ),
        migrations.AddField(
            model_name='leavemanagement',
            name='passport_required_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Passport Required From'),
        ),
        migrations.AddField(
            model_name='leavemanagement',
            name='passport_required_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Passport Required To'),
        ),
    ]
