# Generated by Django 5.2.6 on 2026-01-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0029_leavemanagement_address_during_leave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemanagement',
            name='passport_required_from',
        ),
        migrations.RemoveField(
            model_name='leavemanagement',
            name='passport_required_to',
        ),
    ]
