# Generated by Django 5.2.6 on 2026-02-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0030_remove_leavemanagement_passport_required_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameradepartment',
            name='employee',
        ),
        migrations.AddField(
            model_name='cameradepartment',
            name='file_path',
            field=models.CharField(default='not uploaded', help_text='Path to the file on local system/network', max_length=500),
        ),
    ]
