# Generated by Django 5.2.6 on 2026-02-06 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0031_remove_cameradepartment_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameradepartment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_department_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
