# Generated by Django 5.2.6 on 2026-02-09 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyees', '0032_cameradepartment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_status',
            field=models.CharField(choices=[('active', 'Activ e'), ('on_leave', 'On Leave'), ('probation_period', 'Probation Period'), ('notice_period', 'Notice Period'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
