# Generated by Django 5.2.6 on 2026-01-21 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('client_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('salary_outflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
