# Generated by Django 5.2.6 on 2026-01-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='total_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
