# Generated by Django 5.2.6 on 2026-02-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_monthlyexpensereport_monthlyincomereport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyclientreport',
            name='expected_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='monthlyemployeereport',
            name='expected_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
