# Generated by Django 5.2.6 on 2026-01-30 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Bereavement Leave', 'Bereavement Leave'), ('LOP', 'Leave Without Pay (LOP)'), ('WFH', 'Work From Home (WFH)'), ('Other', 'Other')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reason', models.TextField()),
                ('address_during_leave', models.TextField(blank=True, null=True)),
                ('passport_required_from', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_required_to', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('upcoming', 'Upcoming')], default='pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves_new_admin', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves_new_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Leave Application',
                'verbose_name_plural': 'Admin Leave Applications',
                'ordering': ['-applied_date'],
            },
        ),
    ]
