# Generated by Django 5.2.6 on 2026-02-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_deleted_at_task_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='scheduled_date',
        ),
    ]
