# Generated by Django 5.2.6 on 2026-02-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_taskstep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStep',
        ),
    ]
